Multiple router conditions
Fujicracy/fuji-v2 pull request #425
Opened 2023-04-03 19:52 UTC by DaigaroCota

2023-04-26 16:20 UTC, DaigaroCota commented
This PR is waiting for #446.

2023-05-03 14:00 UTC, pedrovalido approved these changes
Very well done :) Ready to merge unless @brozorec 's answer regarding the scripts says otherwise

2023-05-03 14:35 UTC, pedrovalido requested changes

2023-05-03 14:35 UTC, pedrovalido commented on packages/protocol/script/02_SignBorrow.s.sol
Some tests need fixing
<img width="1728" alt="Screenshot 2023-05-03 at 15 24 01" src="https://user-images.githubusercontent.com/80268365/235948499-a8a07dfc-7207-488a-a632-eabc8c30e42e.png">

2023-05-03 18:33 UTC, pedrovalido commented on packages/protocol/script/02_SignBorrow.s.sol
tests regarding the simple router have been fixed

2023-05-05 11:11 UTC, DaigaroCota commented on packages/protocol/script/02_SignBorrow.s.sol
I updated the scrips to follow the new signing procedure that includes the `actionArgsHash`

2023-05-05 19:59 UTC, DaigaroCota commented
@pedrovalido this is ready to be reviewed again.

2023-05-08 21:25 UTC, merged