Vault rounding and complementary debt functions
Fujicracy/fuji-v2 pull request #487
Opened 2023-04-24 10:38 UTC by DaigaroCota

2023-04-28 16:47 UTC, pedrovalido requested changes
Good job overall :)

2023-04-28 16:47 UTC, pedrovalido commented on packages/protocol/src/interfaces/IVault.sol
> +   */
Dont forget this //TODO

2023-04-28 16:47 UTC, pedrovalido commented on packages/protocol/src/interfaces/IVault.sol
> +   */
Dont forget this //TODO

2023-04-28 16:47 UTC, pedrovalido commented on packages/protocol/src/interfaces/IVault.sol
> +   */
Dont forget this //TODO

2023-04-28 16:47 UTC, pedrovalido commented on packages/protocol/src/interfaces/IVault.sol
> +   * TODO
Dont forget this //TODO

2023-04-28 16:47 UTC, pedrovalido commented on packages/protocol/src/interfaces/IVault.sol
> +   * TODO
Dont forget this //TODO

2023-04-28 16:47 UTC, pedrovalido commented on packages/protocol/src/interfaces/IVault.sol
> +   * TODO
Dont forget this //TODO

2023-04-28 16:47 UTC, pedrovalido commented on packages/protocol/src/interfaces/IVault.sol
> +   * TODO
Dont forget this //TODO

2023-04-28 16:47 UTC, pedrovalido commented on packages/protocol/src/interfaces/IVault.sol
> +   */
Dont forget this //TODO

2023-05-02 19:59 UTC, DaigaroCota commented
@pedrovalido updated all the missing docs in TODOs. This should be ready to be merged.

2023-05-02 20:57 UTC, pedrovalido commented
Great! Let's merge then

2023-05-02 21:09 UTC, merged