Rebalance breaks ltv
Fujicracy/fuji-v2 pull request #499
Opened 2023-04-26 21:05 UTC by pedrovalido

2023-04-28 11:01 UTC, DaigaroCota requested changes

2023-04-28 11:59 UTC, pedrovalido commented on packages/protocol/src/RebalancerManager.sol
> +  function _checkLtvChange(IVault vault, uint256 assets, uint256 debt) internal view {
Current check will be changed to check if Fuji vault will have ltv below max ltv in both provider after rebalance.

2023-04-28 17:16 UTC, pedrovalido commented
Note to self: check the assets==0 revert check. This might have to be removed due to the current path this fix is taking

2023-05-03 09:53 UTC, pedrovalido commented on packages/protocol/src/RebalancerManager.sol
> +  function _checkLtvChange(IVault vault, uint256 assets, uint256 debt) internal view {
@DaigaroCota I have implemented the necessary changes. One thing I am not completely sure is the optimization of the changes I made. Can you check if its efficient?

2023-05-05 11:48 UTC, pedrovalido commented on packages/protocol/src/RebalancerManager.sol
> +
Remove this condition. Check necessary changes to be able to rebalance just debt.

2023-05-05 11:48 UTC, pedrovalido commented on packages/protocol/src/RebalancerManager.sol
> +
![Screenshot 2023-05-05 at 12 28 16](https://user-images.githubusercontent.com/80268365/236446297-a5745b93-cca1-40f2-8baa-f110b972cb4a.png)
use this as an idea. ps: this is the rebalance function inside the borrowing vault.

All the _executeProviderAction should have this condition

2023-05-05 11:48 UTC, pedrovalido commented on packages/protocol/src/RebalancerManager.sol
> +      // revert RebalancerManager__checkLtvChange_invalidAmount();
Remove this comment

2023-05-05 11:48 UTC, pedrovalido commented on packages/protocol/test/mocking/vaults/VaultRebalancing.t.sol
> +        assert(true);
change assert to assert(rebalanceLtv)

2023-05-05 11:48 UTC, pedrovalido commented on packages/protocol/src/RebalancerManager.sol
> +      uint8 debtDecimals = IERC20Metadata(bvault.debtAsset()).decimals();
Read decimals from bvault

2023-05-05 17:30 UTC, pedrovalido commented
All above changes have been addressed. Let me know if it ready to merge @DaigaroCota

2023-05-08 09:58 UTC, merged