Router decoding bug and revert when receiver is router
Fujicracy/fuji-v2 pull request #651
Opened 2023-07-04 20:28 UTC by DaigaroCota

This pull request addresses Item #-25 and #-26 of the Three Sigma security audit.

2023-07-05 09:28 UTC, 0x73696d616f requested changes
Looks good, but there is still a decoding bug in [`_getBeneficiaryFromCalldata()`](https://github.com/Fujicracy/fuji-v2/blob/main/packages/protocol/src/routers/ConnextRouter.sol#L415)

2023-07-05 17:11 UTC, DaigaroCota commented
> Looks good, but there is still a decoding bug in [`_getBeneficiaryFromCalldata()`](https://github.com/Fujicracy/fuji-v2/blob/main/packages/protocol/src/routers/ConnextRouter.sol#L415)

eagle eye 🦅 , thanks for noting 🙌

2023-07-05 22:11 UTC, 0x73696d616f approved these changes
Looks good

2023-07-07 02:18 UTC, pedrovalido approved these changes

2023-07-07 02:25 UTC, merged