VaultSelect infinite loading fixed
Fujicracy/fuji-v2 pull request #702
Opened 2023-08-07 09:40 UTC by NikolaiYurchenko

2023-08-08 07:12 UTC, brozorec requested changes

2023-08-08 10:19 UTC, NikolaiYurchenko commented on packages/frontend/components/Shared/Operation/VaultSelect/VaultSelect.tsx
> +  }, [availableRoutes, collateral.chainId, debt?.chainId]);
changed deps when we have different vault tyles, also fixed folded issue when we were unpating input and routes were folding.

2023-08-08 11:41 UTC, brozorec commented
> changed deps when we have different vault tyles, also fixed folded issue when we were unpating input and routes were folding.

cool, that works @NikolaiYurchenko :+1: 

There might be a similar issue for the charts, both on lending and borrowing:

I start on '/lend' and want to lend WETH on Ethereum.
I switch to USDC and the chart gets updated.
I switch to ETH and the chart stays the same as for USDC.

Tried switching between dai and usdc on borrowing and got into a similar situation.

2023-08-09 19:14 UTC, ferostabio approved these changes

2023-08-10 11:38 UTC, brozorec approved these changes

2023-08-11 04:12 UTC, merged