Authentication
Fujicracy/fuji-v2 pull request #72
Opened 2022-10-06 14:53 UTC by doliG

close #61 

To fix:
- [x] when an unsupported chain is selected, app crashes on load
- [x] when already in the app and select an unsupported chain, no selected value in the dropdown
- [x] when I switch the address from my wallet, it doesn't change the address in the auth bar
- [x] overlapping elements
- [x] When I visit for the first time and I don't have any addresses connected, MM prompts me to connect. The prompt should display only when the user clicks on "Connect Wallet".
- [x] This is not directly related to this PR but when I try to run a production build with yarn build, there is a bunch of errors (lining problems, implicit any and more).

2022-10-07 06:45 UTC, brozorec requested changes
Some issues I spotted:
- when an unsupported chain is selected, app crashes on load
- when already in the app and select an unsupported chain, no selected value in the dropdown
- when I switch the address from my wallet, it doesn't change the address in the auth bar
- overlapping elements 
![image](https://user-images.githubusercontent.com/9572072/194472818-fefcb734-ad1d-4c12-bbc0-ec89fec3b031.png)

2022-10-10 08:08 UTC, brozorec commented
1. The issues [here](https://github.com/Fujicracy/fuji-v2/pull/72#issue-1399800352) are fixed :+1: 

2. However, I found another one. When I visit for the first time and I don't have any addresses connected, MM prompts me to connect. The prompt should display only when the user clicks on "Connect Wallet".

3. This is not directly related to this PR but when I try to run a production build with `yarn build`, there is a bunch of errors (lining problems, implicit `any` and more).

@doliG

2022-10-10 09:46 UTC, Chris-CHEVALIER commented on packages/frontend/components/Header.tsx
> +              )}
Why not using a ternary operator to handle these conditions?

2022-10-10 09:52 UTC, Chris-CHEVALIER commented on packages/frontend/store/index.ts
> +  balance: "",
Balance state is a string, a number or an array?

2022-10-10 09:53 UTC, Chris-CHEVALIER commented on packages/frontend/store/index.ts
> +    console.log(wallets[0])
Don't forget to remove "console.log()" before PR ;)

2022-10-10 09:54 UTC, Chris-CHEVALIER commented on packages/frontend/store/index.ts
> +    if (!wallets[0]) {
Why don't use a try / catch with exception handling?

2022-10-10 16:17 UTC, merged