Compound V2
Fujicracy/fuji-v2 pull request #96
Opened 2022-10-20 10:31 UTC by brozorec

- [ ] add interfaces for cTokens
- [ ] create a `CompoundV2` lending provider contract
- [ ] made `BorrowingVault` payable so that it can support cETH
- [ ] tests

Note: I tried fuzzing "depositAndBorrow" but got this error
![image](https://user-images.githubusercontent.com/9572072/196925198-bc5022e5-30ca-417a-bcea-514f5299de39.png)

2022-10-20 10:36 UTC, brozorec commented
@DaigaroCota what should we put here as an operator?
https://github.com/Fujicracy/fuji-v2/blob/0ba22023e55fbef65f4200efe713cb6c245e9c93/packages/protocol/src/providers/mainnet/CompoundV2.sol#L57

2022-10-20 12:37 UTC, DaigaroCota commented
> @DaigaroCota what should we put here as an operator?
> 
> https://github.com/Fujicracy/fuji-v2/blob/0ba22023e55fbef65f4200efe713cb6c245e9c93/packages/protocol/src/providers/mainnet/CompoundV2.sol#L57

For CompoundV2 it should return the corresponding `asset` equivalent cMarket. In CompoundV2 `vault` can just be ignored.
> `function approvedOperator(address asset, address vault) external view returns (address operator);`

Recall that this is needed in the vault when `setActiveProvider()`:
https://github.com/Fujicracy/fuji-v2/blob/a2aa239317274fae15aea580a30a58ca5ce7494d/packages/protocol/src/abstracts/BaseVault.sol#L490

2022-10-24 20:26 UTC, DaigaroCota requested changes
Hey @brozorec, the following test: `test_paybackAndWithdraw` for `~packages/protocol/test/mainnet/compoundV2/Provider.t.sol` is not passing.

![image](https://user-images.githubusercontent.com/32775237/197621483-e2f5d761-5168-492b-a834-74b9e02d8a31.png)

This is because when you set the `ActiveProvider` by calling `setActiveProvider()` the BorrowingVault is not giving ERC20-approval for the `debtAsset`. This means that in BorrowingVault we need to override the `setActiveProvider()` function and grant infinite approval for both the asset and debtAsset. This could be a bit tricky given that the signature of ILendingProvider changed a bit for `approvedOperator()`.

2022-10-25 13:24 UTC, DaigaroCota approved these changes

2022-10-25 13:25 UTC, merged